version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/var/compilerbook
    working_dir: /var/compilerbook
